#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDriveMotor, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightDriveMotor, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
const float wheelDi = 2.930;
float wheelCir;
float ticksPerInch;
const float rampLength = 102;
float rampLengthTicks;
int LineDis = 102;
float LineDisTick;

void initializeRobot()
{

	disableDiagnosticsDisplay();
	wheelCir=wheelDi * 3.1415926;
	ticksPerInch = 1440 / wheelCir;
	rampLengthTicks = rampLength * ticksPerInch;
	LineDisTick = LineDis * ticksPerInch;
	nMotorEncoder[RightDriveMotor] = 0;
	nMotorEncoder[LeftDriveMotor] = 0;
	nxtDisplayBigTextLine(2, "%d",LineDisTick);
	return;

}

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.


	nMotorEncoderTarget[RightDriveMotor] = LineDisTick;
	motor[RightDriveMotor]= 100;
	nMotorEncoderTarget[LeftDriveMotor] = LineDisTick;
	motor[LeftDriveMotor] = 100;

	while(nMotorRunState[RightDriveMotor] != runStateIdle){
		nxtDisplayBigTextLine(5, "%d", nMotorEncoder[RightDriveMotor]);
	}
	motor[RightDriveMotor] = 0;
	motor[LeftDriveMotor] = 0;
}
