#pragma config(Motor,  motorA,          LeftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          RightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[LeftMotor] = 85;
motor[RightMotor] = 85;
wait1Msec(5000);
}
