#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDriveMotor, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightDriveMotor, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RollerMotor,   tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     ArmMotor,      tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    HookLeft,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    HookRight,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
const float wheelDi = 2.930;
float wheelCir;
float ticksPerInch;
const float rampLength = 95;
float rampLengthTicks;
float ArmTarget = 4000;


void initializeRobot()
{
	wheelCir=wheelDi * 3.1415926;
	ticksPerInch = 1440 / wheelCir;
	rampLengthTicks = rampLength * ticksPerInch;
	nMotorEncoder[RightDriveMotor] = 0;
	nMotorEncoder[LeftDriveMotor] = 0;
	nMotorEncoder[ArmMotor] = 0;
	return;
}



task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

		servo[HookRight] = 20;
		servo[HookLeft] = 205;

		nMotorEncoderTarget[ArmMotor] = ArmTarget;
		wait1Msec(50);
		motor[ArmMotor] = 50;

		nMotorEncoderTarget[RightDriveMotor] = rampLengthTicks;//
		wait1Msec(50);																				 //
		motor[RightDriveMotor]= 100;												   //drive off
		nMotorEncoderTarget[LeftDriveMotor] = rampLengthTicks; //
		wait1Msec(50);																				 //the ramp
		motor[LeftDriveMotor] = 100;													 //

		while(nMotorRunState[RightDriveMotor] != runStateIdle && nMotorRunState[LeftDriveMotor] != runStateIdle){
		nxtDisplayTextLine(1,"RightDriveMotor = %d", nMotorEncoder[RightDriveMotor]);
		nxtDisplayTextLine(2,"LeftDriveMotor = %d", nMotorEncoder[LeftDriveMotor]);
		wait1Msec(50);
		}
		motor[RightDriveMotor] = 0;
		motor[LeftDriveMotor] = 0;

		nMotorEncoderTarget[ArmMotor] = 7800;
		wait1Msec(50);
		motor[ArmMotor] = 50;
		while(nMotorRunState[ArmMotor] != runStateIdle){
		nxtDisplayTextLine(3,"ArmMotor = %d", nMotorEncoder[ArmMotor]);
		wait1Msec(50);
		}
		wait1Msec(5000);
	nMotorEncoderTarget[ArmMotor] = 7800;
	wait1Msec(50);
	motor[ArmMotor] = -50;
	while(nMotorRunState[ArmMotor] != runStateIdle){
		nxtDisplayTextLine(3,"ArmMotor = %d", nMotorEncoder[ArmMotor]);
		wait1Msec(50);
	}
}
