#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDriveMotor, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightDriveMotor, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RollerMotor,   tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     ArmMotor,      tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
const float wheelDi = 2.930;
float wheelCir;
float ticksPerInch;
const float rampLength = 102;
float rampLengthTicks;
float ArmTarget = 10000;


void initializeRobot()
{
	wheelCir=wheelDi * 3.1415926;
	ticksPerInch = 1440 / wheelCir;
	rampLengthTicks = rampLength * ticksPerInch;
	nMotorEncoder[RightDriveMotor] = 0;
	nMotorEncoder[LeftDriveMotor] = 0;
	return;
}



task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.
	{
		nMotorEncoderTarget[ArmMotor] = ArmTarget;

	motor[ArmMotor] = 50;
	wait1Msec(100);

		nMotorEncoderTarget[RightDriveMotor] = rampLengthTicks;//
		motor[RightDriveMotor]= 36;												   //drive off
		nMotorEncoderTarget[LeftDriveMotor] = rampLengthTicks; //the ramp
		motor[LeftDriveMotor] = 36;														 //

	while(nMotorRunState[RightDriveMotor] != runStateIdle && nMotorRunState[LeftDriveMotor] != runStateIdle){
	}
	motor[RightDriveMotor] = 0;
		motor[LeftDriveMotor] = 0;
}
}
